branches:
  only:
  - backup

language: node_js

sudo: false

node_js:
    - 'stable'

before_install:
- git config --global user.name "travis.org"
- git config --global user.email fjjwlzd@163.com
- git clone -b backup https://github.com/DoubleShift/DoubleShift.github.io.git
- cd DoubleShift.github.io

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g


after_script:
 - cd ./public
 - git init
 - git config user.name "Travis.org"
 - git config user.email "fjjwlzd@163.com"
 - git add .
 - git commit -m "Update"
 - git push "https://${GH_TOKEN}@${GH_REF}" master:master
