branches:
  only:
  - backup

language: node_js

sudo: false

node_js:
    - 'stable'

before_install:
- git config --global user.name "travis.org"
- git config --global user.email fjjwlzd@163.com
- git clone -b backup https://github.com/DoubleShift/DoubleShift.github.io.git
- cd DoubleShift.github.io

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g


after_script:		
	
- git config user.name "Travis.org"		
- git config user.email "fjjwlzd@163.com"		
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo d
